# Generated by Django 4.1 on 2022-08-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
