# Generated by Django 4.1 on 2022-08-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0002_alter_contacts_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='fullname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
