# Generated by Django 4.1 on 2022-08-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0004_alter_image_email_alter_image_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
