# Generated by Django 4.1 on 2022-08-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0005_alter_image_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='email',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
