# Generated by Django 4.1 on 2022-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0006_alter_image_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
